.PHONY: FORCE
all: FORCE
	$(MAKE) -C .. endlesscoin_qt test_endlesscoin_qt
clean: FORCE
	$(MAKE) -C .. endlesscoin_qt_clean test_endlesscoin_qt_clean
check: FORCE
	$(MAKE) -C .. test_endlesscoin_qt_check
endlesscoin-qt endlesscoin-qt.exe: FORCE
	 $(MAKE) -C .. endlesscoin_qt
